#服务端口
server:
  port: 8002
  #服务名
  #环境设置：dev、test、prod
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tA5SQpirarcggqNGo1F
      keysecret: t0DVGgiXwR8uI2ZSxvbGLRtpKZahID
      bucketname: solitude-kx


  #阿里云 OSS
  #不同的服务器，地址不同

  #bucket可以在控制台创建，也可以使用java代码创建
spring:
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

