server:
  port: 8009

spring:
  application:
    name: service-acl
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: kx5254
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.109.137
    port: 6379
    database: 0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/kx/aclservice/mapper/xml/*.xml
